# Generated by Django 2.1.4 on 2019-01-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='betting.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='betting.Sport'),
        ),
        migrations.AlterField(
            model_name='market',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='betting.Sport'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.Market'),
        ),
    ]
